### PR TITLE
fix: bump package info plus

### LINKED ISSUE #2: Update package_info_plus to 3.1.1
Bump the version of `package_info_plus` to 3.1.1

### PR DESCRIPTION
**Pull request by Kiruel**
Adding full code of the SDK, (current version 1.1.0) and bump `package_info_plus` to 3.1.1 
fix #2

### CODE REVIEW

**Comment by Kiruel** [comment]
Hi @docstun can you take a look ? Thanks.

**Comment by Kiruel** [comment]
Alright thanks @theSoenke , yeah I think it can be nice to have the possibility to make some PRs directly on this repo ;) ! 
Cheers,

**Comment by theSoenke** [comment]
@Kiruel as a first step version 1.1.1 has now been published with a relaxed version constraint for `package_info_plus`

**Comment by docstun** [comment]
Closed since original issue seems resolved 🙂

**Pull request closed without merging**
